In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../dataset/Hotel_Reviews.csv')

In [5]:
df.shape

(515738, 17)

In [6]:
df.head(1)

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968

In [16]:
negative = df['Negative_Review'].value_counts().reset_index()
positive = df['Positive_Review'].value_counts().reset_index()

In [17]:
negative

                                          Negative_Review   count
0                                             No Negative  127890
1                                                 Nothing   14295
2                                                Nothing     4236
3                                                 nothing    2225
4                                                     N A    1037
...                                                   ...     ...
330006   No parking Public parking garage is 15 Euro p...       1
330007   no trolly or staff to help you take the lugga...       1
330008           The hotel looks like 3 but surely not 4        1
330009   The ac was useless It was a hot week in vienn...       1
330010       I was in 3rd floor It didn t work Free Wife        1

[330011 rows x 2 columns]

In [18]:
negative.head(2)

  Negative_Review   count
0     No Negative  127890
1         Nothing   14295

In [22]:
negative['status'] = 0
positive['status'] = 1

In [25]:
negative

                                          Negative_Review   count  status
0                                             No Negative  127890       0
1                                                 Nothing   14295       0
2                                                Nothing     4236       0
3                                                 nothing    2225       0
4                                                     N A    1037       0
...                                                   ...     ...     ...
330006   No parking Public parking garage is 15 Euro p...       1       0
330007   no trolly or staff to help you take the lugga...       1       0
330008           The hotel looks like 3 but surely not 4        1       0
330009   The ac was useless It was a hot week in vienn...       1       0
330010       I was in 3rd floor It didn t work Free Wife        1       0

[330011 rows x 3 columns]

In [26]:
negative.head(1)

  Negative_Review   count  status
0     No Negative  127890       0

In [28]:
positive.head(1)

  Positive_Review  count  status
0     No Positive  35946       1

In [29]:
negative.info()

<class 'pandas.DataFrame'>
RangeIndex: 330011 entries, 0 to 330010
Data columns (total 3 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Negative_Review  330011 non-null  str
 1   count            330011 non-null  int64
 2   status           330011 non-null  int64
dtypes: int64(2), str(1)
memory usage: 7.6 MB

In [30]:
positive.info()

<class 'pandas.DataFrame'>
RangeIndex: 412601 entries, 0 to 412600
Data columns (total 3 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Positive_Review  412601 non-null  str
 1   count            412601 non-null  int64
 2   status           412601 non-null  int64
dtypes: int64(2), str(1)
memory usage: 9.4 MB

In [31]:
negative = negative[negative['count']==1]
positive = positive[positive['count']==1]

In [32]:
negative.info()

<class 'pandas.DataFrame'>
RangeIndex: 323546 entries, 6465 to 330010
Data columns (total 3 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Negative_Review  323546 non-null  str
 1   count            323546 non-null  int64
 2   status           323546 non-null  int64
dtypes: int64(2), str(1)
memory usage: 7.4 MB

In [33]:
negative.shape

(323546, 3)

In [34]:
positive.shape

(403184, 3)

In [35]:
negative = negative.rename(columns={'Negative_Review': 'text'})
positive = positive.rename(columns={'Positive_Review': 'text'})

In [37]:
negative.head(1)

                                                   text  count  status
6465   I am so angry that i made this post available...      1       0

In [41]:
positive.head(2)

                                                   text  count  status
9417   Only the park outside of the hotel was beauti...      1       1
9418   No real complaints the hotel was great great ...      1       1

In [42]:
positive.to_csv('../dataset/positive.csv', index=False)
negative.to_csv('../dataset/negative.csv', index=False)